version: "3.1"
services:
  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - xcloud
      - xnode
  xnode:
    build: ./nodeApp
    restart: always
    depends_on:
      - xcloud
  xcloud:
    build: ./apache
  xdb:
    image: mongo
    ports:
      - "27096:27017"
  #Might add a xauth later if need be 
